name: Publish Schema to BSR

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pull-requests: write

jobs:
  publish-to-bsr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: bufbuild/buf-action@v1.3
        with:
          token: ${{ secrets.BUF_TOKEN }}
          setup_only: true

      - name: Lint
        run: buf lint

      - name: Format
        run: buf format

      - name: Push
        run: buf push --error-format github-actions --create --git-metadata
