name: Publish Schema to BSR

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pull-requests: write

jobs:
  publish-to-bsr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: bufbuild/buf-action@v1.3
        with:
          input: proto/
          token: ${{ secrets.BUF_TOKEN }}
          lint: true
          format: true
          breaking: true
          push: true
